### PR TITLE
TBCC Fix

### PR DESCRIPTION
**Pull request by Ann0n**
A fix for the dropdown menu in TBCC.

### CODE REVIEW

**Comment by Ann0n** [comment]
This is missing the other fix I made.

**Comment by cdmichaelb** [comment]
I'm testing these changes locally. Did you mistakenly close the pull request or is there something else you wanted to add?

**Comment by Ann0n** [comment]
The dropdown from minimap icon is fixed with that, but other things are still broke.
For example the create new outfit.

I had a few different patches, however I messed up my local repository.
I thought I would try adding them directly on github, but i never did that before.
I really wanted to put them out together.
I ended up running out of time for today.
I wont be able to get back to it until Monday, since I am busy with RL this weekend.

Playing a druid without Outfitter is a chore :P

From: cdmichaelb ***@***.***>
Reply to: cdmichaelb/Outfitter ***@***.***>
Date: Saturday, 22. May 2021 at 02:52
To: cdmichaelb/Outfitter ***@***.***>
Cc: Ann0n ***@***.***>, State change ***@***.***>
Subject: Re: [cdmichaelb/Outfitter] TBCC Fix (#60)


I'm testing these changes locally. Did you mistakenly close the pull request or is there something else you wanted to add?

**Comment by cdmichaelb** [comment]
Ah ok, I will do my best to have a fix before Monday.

**Pull request closed without merging**
